-- This file imports all test modules
import Clean.Utils.Test.TestDecomposeProvableStruct
import Clean.Utils.Test.TestSplitProvableStructEq
import Clean.Utils.Test.TestCircuitProofStart
import Clean.Utils.Test.TestSimplifyProvableStructEval
import Clean.Utils.Test.TestWitgenEvalProjection
import Clean.Utils.Test.TestElaborateCircuit
import Clean.Utils.Test.TestCircuitStructDeriving
import Clean.Utils.Test.TestMixedCircuitType
import Clean.Utils.Test.TestLookup
import Clean.Utils.Test.SimpMatchRegression
import Clean.Halo2.Tests.TestProvableTypeSimp
import Clean.Halo2.Tests.TestCircuitTypeDeriving
import Clean.Halo2.Tests.TestSubcircuit
import Clean.Halo2.Tests.TestLayouterSubcircuit
import Clean.Halo2.Tests.TestSubcircuitRw
import Clean.Halo2.Tests.TestAbstractOutputs
import Clean.Halo2.Tests.TestLoops
import Clean.Halo2.Tests.TestContractBridges
import Clean.Halo2.Tests.TestLookupMembership
import Clean.Halo2.Tests.TestProofStart
import Clean.Halo2.Tests.TestTupleLookup
import Clean.Ironwood.Tests.TestVkMatchAdd
import Clean.Ironwood.Tests.TestVkMatchMul
import Clean.Ironwood.Tests.TestVkMatchBaseField
import Clean.Ironwood.Tests.TestVkMatchFullWidth
import Clean.Ironwood.Tests.TestVkMatchShort
import Clean.Ironwood.Tests.TestVkMatchAction
import Clean.Ironwood.Tests.TestVkLayoutAction
import Clean.Ironwood.Tests.TestVkLayoutActionBase
import Clean.Ironwood.Tests.TestVkMatchSinsemilla
import Clean.Ironwood.Tests.TestVkMatchMerkle
import Clean.Ironwood.Tests.TestVkLayoutMul
import Clean.Ironwood.Tests.TestVkLayoutBaseField
import Clean.Ironwood.Tests.TestVkLayoutFullWidth
import Clean.Ironwood.Tests.TestVkLayoutShort
import Clean.Ironwood.Tests.TestVkLayoutSinsemilla
import Clean.Ironwood.Tests.TestVkLayoutMerkle
import Clean.Ironwood.Tests.TestVkLayoutPoseidon
import Clean.Ironwood.Tests.TestVkLayoutNoteCommit
