import Clean.Halo2.Synthesis

/-!
# Clean-like formal semantics for Halo2 circuits

This module is the beginning of the proof-facing Halo2 layer.  The names mirror
Clean's core vocabulary (`Operation`, `Circuit`, `FormalCircuit`) while keeping
Halo2's row/column arithmetization explicit: cells are addressed by columns and
rows, gates are evaluated at rows with rotations, and copy constraints are first
class operations rather than being erased into ordinary equality assertions.
-/

namespace Halo2

open Halo2.Pinned

/-- A concrete assignment for a Halo2 arithmetization trace.  Rows are integers
so that rotations are interpreted directly; well-formed circuits can separately
rule out invalid negative accesses if needed. -/
structure Trace (F : Type) where
  advice : Nat → Int → F
  fixed : Nat → Int → F
  instanceValue : Nat → Int → F
  constant : String → F

namespace Trace

variable {F : Type}

/-- Evaluate a concrete Halo2 cell in a trace. -/
def evalCell (t : Trace F) (cell : Synthesis.Cell) : F :=
  match cell.column.columnType with
  | ColumnKind.Advice => t.advice cell.column.index cell.row
  | ColumnKind.Fixed => t.fixed cell.column.index cell.row
  | ColumnKind.Instance => t.instanceValue cell.column.index cell.row

end Trace

namespace Pinned.Expression

/-- Evaluate a pinned Halo2 expression at a particular base row.  Query indices
are metadata and do not affect semantics; column, kind, and rotation do. -/
def eval {F : Type} [Ring F] (trace : Trace F) (row : Int) : Expression → F
  | .constant c => trace.constant c
  | .selector i => trace.fixed i row
  | .fixed _ column (.rot r) => trace.fixed column (row + r)
  | .advice _ column (.rot r) => trace.advice column (row + r)
  | .instance _ column (.rot r) => trace.instanceValue column (row + r)
  | .negated e => - eval trace row e
  | .sum a b => eval trace row a + eval trace row b
  | .product a b => eval trace row a * eval trace row b
  | .scaled e c => eval trace row e * trace.constant c

end Pinned.Expression

/-- Halo2 operations, with Clean-like naming but Halo2-native structure. -/
inductive Operation where
  /-- A custom-gate polynomial evaluated at a concrete row. -/
  | gate : Nat → Pinned.Expression → Operation
  /-- A Halo2 copy/permutation edge.  This is intentionally not represented as
  an ordinary gate assertion, even though satisfaction implies equality of the
  two assigned values. -/
  | wire : Synthesis.Cell → Synthesis.Cell → Operation
  /-- A fixed-column assignment generated by layout/table assignment. -/
  | fixed : Synthesis.Cell → String → Operation
  /-- A lookup argument at a row.  Its semantics is supplied by the trace-local
  lookup predicate, so the core DSL can support different table interpretations. -/
  | lookup : Nat → List Pinned.Expression → List Pinned.Expression → Operation
  deriving Repr, DecidableEq, BEq

namespace Operation

/-- Clean-style alias for a Halo2 custom-gate assertion at a concrete row. -/
def assert (row : Nat) (expr : Pinned.Expression) : Operation :=
  .gate row expr

/-- Semantic satisfaction of one Halo2 operation. -/
def Satisfied {F : Type} [Ring F]
    (lookup : List F → List F → Prop) (trace : Trace F) : Operation → Prop
  | .gate row expr => expr.eval trace row = 0
  | .wire left right => trace.evalCell left = trace.evalCell right
  | .fixed cell value => trace.evalCell cell = trace.constant value
  | .lookup row inputs table =>
      lookup (inputs.map (Pinned.Expression.eval trace row))
        (table.map (Pinned.Expression.eval trace row))

@[simp]
theorem gate_satisfied {F : Type} [Ring F] {lookup : List F → List F → Prop}
    {trace : Trace F} {row : Nat} {expr : Pinned.Expression} :
    Operation.Satisfied lookup trace (.gate row expr) ↔ expr.eval trace row = 0 :=
  Iff.rfl

@[simp]
theorem wire_satisfied {F : Type} [Ring F] {lookup : List F → List F → Prop}
    {trace : Trace F} {left right : Synthesis.Cell} :
    Operation.Satisfied lookup trace (.wire left right) ↔ trace.evalCell left = trace.evalCell right :=
  Iff.rfl

@[simp]
theorem fixed_satisfied {F : Type} [Ring F] {lookup : List F → List F → Prop}
    {trace : Trace F} {cell : Synthesis.Cell} {value : String} :
    Operation.Satisfied lookup trace (.fixed cell value) ↔ trace.evalCell cell = trace.constant value :=
  Iff.rfl

@[simp]
theorem lookup_satisfied {F : Type} [Ring F] {lookup : List F → List F → Prop}
    {trace : Trace F} {row : Nat} {inputs table : List Pinned.Expression} :
    Operation.Satisfied lookup trace (.lookup row inputs table) ↔
      lookup (inputs.map (Pinned.Expression.eval trace row))
        (table.map (Pinned.Expression.eval trace row)) :=
  Iff.rfl

end Operation

/-- A Halo2 circuit as a list of proof-facing operations.  This intentionally
resembles Clean's `Circuit`, but its operations are Halo2-native. -/
structure Circuit where
  operations : List Operation := []
deriving Repr, DecidableEq, BEq

namespace Circuit

instance : EmptyCollection Circuit where
  emptyCollection := {}

/-- Append one operation to a Halo2 circuit. -/
def push (c : Circuit) (op : Operation) : Circuit :=
  { c with operations := c.operations ++ [op] }

/-- A one-operation custom-gate circuit. -/
def gate (row : Nat) (expr : Pinned.Expression) : Circuit :=
  { operations := [Operation.gate row expr] }

/-- Clean-style name for a one-operation Halo2 assertion circuit. -/
def assertZero (row : Nat) (expr : Pinned.Expression) : Circuit :=
  gate row expr

/-- A one-operation wire/copy-constraint circuit. -/
def wire (left right : Synthesis.Cell) : Circuit :=
  { operations := [Operation.wire left right] }

/-- A one-operation fixed-assignment circuit. -/
def fixed (cell : Synthesis.Cell) (value : String) : Circuit :=
  { operations := [Operation.fixed cell value] }

/-- A one-operation lookup circuit. -/
def lookup (row : Nat) (inputs table : List Pinned.Expression) : Circuit :=
  { operations := [Operation.lookup row inputs table] }

/-- Append many operations to a Halo2 circuit. -/
def append (c d : Circuit) : Circuit :=
  { operations := c.operations ++ d.operations }

instance : Append Circuit where
  append := append

/-- Semantic satisfaction of a Halo2 circuit. -/
def Satisfied {F : Type} [Ring F]
    (c : Circuit) (lookup : List F → List F → Prop) (trace : Trace F) : Prop :=
  ∀ op ∈ c.operations, op.Satisfied lookup trace

@[simp]
theorem empty_satisfied {F : Type} [Ring F] {lookup : List F → List F → Prop}
    {trace : Trace F} :
    ({ operations := [] } : Circuit).Satisfied lookup trace := by
  intro op h
  cases h

theorem append_satisfied {F : Type} [Ring F] {lookup : List F → List F → Prop}
    {trace : Trace F} {c d : Circuit} :
    (c ++ d).Satisfied lookup trace ↔ c.Satisfied lookup trace ∧ d.Satisfied lookup trace := by
  constructor
  · intro h
    constructor
    · intro op hop
      apply h op
      change op ∈ c.operations ++ d.operations
      exact List.mem_append_left d.operations hop
    · intro op hop
      apply h op
      change op ∈ c.operations ++ d.operations
      exact List.mem_append_right c.operations hop
  · intro h op hop
    rcases h with ⟨hc, hd⟩
    change op ∈ c.operations ++ d.operations at hop
    rcases List.mem_append.mp hop with hopLeft | hopRight
    · exact hc op hopLeft
    · exact hd op hopRight

/-- Create gate operations by checking every gate at every row. -/
def gatesFromConstraintSystem (cs : ConstraintSystem) (numRows : Nat) : Circuit :=
  { operations := List.flatten ((List.range numRows).map fun row =>
      cs.gates.map (fun gate => Operation.gate row gate)) }

/-- Create lookup operations by checking every lookup argument at every row. -/
def lookupsFromConstraintSystem (cs : ConstraintSystem) (numRows : Nat) : Circuit :=
  { operations := List.flatten ((List.range numRows).map fun row =>
      cs.lookups.map (fun lookup => Operation.lookup row lookup.inputExpressions lookup.tableExpressions)) }

/-- Proof-facing operations generated directly from pinned constraint-system metadata. -/
def fromConstraintSystem (cs : ConstraintSystem) (numRows : Nat) : Circuit :=
  gatesFromConstraintSystem cs numRows ++ lookupsFromConstraintSystem cs numRows

/-- Fixed assignments as proof-facing operations. -/
def fixedAssignments (assignments : List (Synthesis.Cell × String)) : Circuit :=
  { operations := assignments.map (fun (cell, value) => Operation.fixed cell value) }

/-- Copy constraints as proof-facing wire operations. -/
def wires (copies : List (Synthesis.Cell × Synthesis.Cell)) : Circuit :=
  { operations := copies.map (fun (left, right) => Operation.wire left right) }

/-- Convert a configured Halo2 circuit to the proof-facing operation list that is
visible from configuration and synthesis/layout metadata. -/
def fromConfigured {Config : Type} (c : Synthesis.ConfiguredCircuit Config) : Circuit :=
  let layout := c.synthesize c.config
  let rows := max 1 (max (Synthesis.activationRows layout.selectorActivations) layout.usedRows)
  fromConstraintSystem c.cs rows ++ fixedAssignments layout.fixedAssignments ++ wires layout.copyConstraints

end Circuit

/-- Soundness statement for a Halo2 circuit: under assumptions, satisfying the
Halo2-native operations implies the Lean-level spec. -/
def Soundness {F : Type} [Ring F] (circuit : Circuit) (lookup : List F → List F → Prop)
    (Assumptions Spec : Trace F → Prop) : Prop :=
  ∀ {trace : Trace F}, Assumptions trace → circuit.Satisfied lookup trace → Spec trace

/-- A proof-carrying Halo2 circuit, mirroring Clean's `FormalCircuit` idea:
`circuit` is the Halo2 arithmetization, `Assumptions` are preconditions on the
trace, `Spec` is a Lean predicate over traces, and `soundness` proves that
satisfying the Halo2 operations implies the spec.  Unlike Clean's ordinary
`FormalCircuit`, this intentionally does not package completeness yet: Daira's
plan only needs knowledge soundness at this layer. -/
structure FormalCircuit (F : Type) [Ring F] where
  name : String := "anonymous"
  circuit : Circuit
  lookup : List F → List F → Prop := fun _ _ => True
  Assumptions : Trace F → Prop := fun _ => True
  Spec : Trace F → Prop
  soundness : Soundness circuit lookup Assumptions Spec

namespace FormalCircuit

/-- Use the soundness proof packaged in a `FormalCircuit`. -/
theorem sound {F : Type} [Ring F] (c : FormalCircuit F) {trace : Trace F}
    (hAssumptions : c.Assumptions trace)
    (h : c.circuit.Satisfied c.lookup trace) : c.Spec trace :=
  c.soundness hAssumptions h

end FormalCircuit

end Halo2
