-- Auto-generated by `layout_dump::dump_layout_full_width` (sibling halo2 checkout).
-- Selector-compression map for the isolated fullWidth chain. Do not edit by hand.
import Clean.Halo2.Fixtures.FixtureTypes

namespace Halo2.Fixtures

open Halo2.Fixtures

def fullWidthSelMap : SelCompressMap :=
  { newFixedCols := 3,
    entries := [(0, ⟨10, 2, 1⟩),
      (1, ⟨10, 2, 2⟩),
      (2, ⟨11, 1, 1⟩),
      (3, ⟨12, 1, 1⟩)] }

end Halo2.Fixtures
