-- Auto-generated by `orchard::circuit::note_commit::layout_dump::dump_layout_note_commit`
-- (sibling orchard checkout; see orchard/src/circuit/layout_dump.rs). Do not edit by hand.
-- Regenerate:
--   cargo test -p orchard --lib circuit::note_commit::layout_dump --features circuit --release -- --nocapture
import Clean.Halo2.Fixtures.FixtureTypes

namespace Halo2.Fixtures

open Halo2.Fixtures

def noteCommitSelMap : SelCompressMap :=
  { newFixedCols := 10,
    entries := [(0, ⟨14, 1, 1⟩),
      (1, ⟨15, 1, 1⟩),
      (3, ⟨16, 1, 1⟩),
      (2, ⟨17, 6, 1⟩),
      (4, ⟨17, 6, 2⟩),
      (5, ⟨17, 6, 3⟩),
      (6, ⟨17, 6, 4⟩),
      (7, ⟨17, 6, 5⟩),
      (8, ⟨17, 6, 6⟩),
      (9, ⟨18, 7, 1⟩),
      (10, ⟨18, 7, 2⟩),
      (11, ⟨18, 7, 3⟩),
      (12, ⟨18, 7, 4⟩),
      (13, ⟨18, 7, 5⟩),
      (14, ⟨18, 7, 6⟩),
      (15, ⟨18, 7, 7⟩),
      (16, ⟨19, 4, 1⟩),
      (17, ⟨19, 4, 2⟩),
      (18, ⟨19, 4, 3⟩),
      (19, ⟨19, 4, 4⟩),
      (20, ⟨20, 6, 1⟩),
      (21, ⟨20, 6, 2⟩),
      (22, ⟨20, 6, 3⟩),
      (23, ⟨20, 6, 4⟩),
      (24, ⟨20, 6, 5⟩),
      (25, ⟨20, 6, 6⟩),
      (26, ⟨21, 5, 1⟩),
      (27, ⟨21, 5, 2⟩),
      (28, ⟨21, 5, 3⟩),
      (31, ⟨21, 5, 4⟩),
      (32, ⟨21, 5, 5⟩),
      (29, ⟨22, 1, 1⟩),
      (30, ⟨23, 1, 1⟩)] }

end Halo2.Fixtures
