import Clean.Halo2.Orchard

/-!
# Exact Rust pinned-CS fixtures

These strings are generated by `halo2_proofs::plonk::VerifyingKey::pinned()`.
The value-commitment fixture comes from the local Orchard ECC probe; the full
action fixture is Orchard's checked-in `circuit_description_fixed` with the `cs`
portion extracted.
-/

namespace Halo2.Fixtures.RustPinnedCS

/-- The `cs: PinnedConstraintSystem { ... }` target for the Orchard
value-commitment ECC gadget circuit. -/
def orchardValueCommit : String :=
  include_str "orchard_value_commit_rust_pinned_cs.txt"

/-- The full Orchard action circuit `cs: PinnedConstraintSystem { ... }` target. -/
def orchardAction : String :=
  include_str "orchard_action_rust_pinned_cs.txt"

end Halo2.Fixtures.RustPinnedCS
