-- Auto-generated by `layout_dump::dump_layout_short` (sibling halo2 checkout).
-- Selector-compression map for the isolated short chain. Do not edit by hand.
import Clean.Halo2.Fixtures.FixtureTypes

namespace Halo2.Fixtures

open Halo2.Fixtures

def shortSelMap : SelCompressMap :=
  { newFixedCols := 2,
    entries := [(0, ⟨10, 3, 1⟩),
      (1, ⟨10, 3, 2⟩),
      (3, ⟨10, 3, 3⟩),
      (2, ⟨11, 1, 1⟩)] }

end Halo2.Fixtures
