-- Auto-generated by halo2 `dump_lean` (Halo2-Clean VK-matching). Do not edit by hand.
-- Selector-compression map (see `compress_selectors.rs`): per selector, the packed
-- fixed column, its combination length, and this selector's assigned root.
import Clean.Halo2.Fixtures.FixtureTypes

namespace Halo2.Fixtures

open Halo2.Fixtures

def sinsemillaSelMap : SelCompressMap :=
  { newFixedCols := 5,
    entries := [(0, ⟨6, 1, 1⟩),
      (1, ⟨7, 1, 1⟩),
      (2, ⟨9, 2, 1⟩),
      (3, ⟨8, 1, 1⟩),
      (4, ⟨10, 1, 1⟩),
      (5, ⟨9, 2, 2⟩)] }

end Halo2.Fixtures
