-- Auto-generated by halo2 `dump_lean` (Halo2-Clean VK-matching). Do not edit by hand.
-- Chain: orchard merkle_config_1 prerequisites + the real `SinsemillaChip::configure`.
-- Exact Rust calls, in order (halo2_gadgets/src/sinsemilla/dump.rs::register_prereqs):
--   meta.advice_column() x10; meta.fixed_column() + meta.enable_constant() (constants);
--   meta.fixed_column() (fixed_y_q); meta.lookup_table_column() x3;
--   PallasLookupRangeCheckConfig::configure(meta, advices[9], lookup.0);
--   SinsemillaChip::configure(meta, advices[0..5], advices[6], fixed_y_q, lookup,
--     range_check, /*allow_init_from_private_point=*/ false).
-- Post-compression activations gathered from `SinsemillaDumpCircuit::synthesize` (one real
-- `hash_to_point` + the b_1/b_2 short range checks, Value::unknown witnesses, k=11).
-- Regenerate: cargo run -p halo2_gadgets --features dump-lean --bin dump_lean_sinsemilla -- <out_dir>
-- Selector-compression map (see `compress_selectors.rs`): per selector, the packed
-- fixed column, its combination length, and this selector's assigned root.
import Clean.Halo2.Fixtures.FixtureTypes

namespace Halo2.Fixtures

open Halo2.Fixtures

def sinsemillaSelMap : SelCompressMap :=
  { newFixedCols := 5,
    entries := [(0, ⟨6, 1, 1⟩),
      (1, ⟨7, 1, 1⟩),
      (2, ⟨9, 1, 1⟩),
      (3, ⟨8, 1, 1⟩),
      (4, ⟨10, 1, 1⟩)] }

end Halo2.Fixtures
