-- Auto-generated by the sibling-checkout `ecc::chip::layout_dump::dump_layout_add`.
-- Do not edit by hand. Regenerate:
--   cargo test --release -p halo2_gadgets --lib ecc::chip::layout_dump::dump_layout_add -- --nocapture
import Clean.Ironwood.Fixtures.FixtureTypes

namespace Halo2.Ironwood.Fixtures

open Halo2.Ironwood.Fixtures

def addSelMap : SelCompressMap :=
  { newFixedCols := 1,
    entries := [(0, ⟨0, 1, 1⟩)] }

end Halo2.Ironwood.Fixtures
