-- Auto-generated by `layout_dump::dump_layout_base_field` (sibling halo2 checkout).
-- Selector-compression map for the isolated base-field-elem chain. Do not edit by hand.
import Clean.Ironwood.Fixtures.FixtureTypes

namespace Halo2.Ironwood.Fixtures

open Halo2.Ironwood.Fixtures

def baseFieldSelMap : SelCompressMap :=
  { newFixedCols := 4,
    entries := [(0, ⟨11, 1, 1⟩),
      (1, ⟨12, 1, 1⟩),
      (2, ⟨13, 4, 1⟩),
      (3, ⟨13, 4, 2⟩),
      (4, ⟨13, 4, 3⟩),
      (6, ⟨13, 4, 4⟩),
      (5, ⟨14, 1, 1⟩)] }

end Halo2.Ironwood.Fixtures
