-- Auto-generated by halo2 `dump_lean` (Halo2-Clean VK-matching). Do not edit by hand.
-- Chain: the Sinsemilla prerequisite chain (see sinsemillaPre) continued by the real
-- `MerkleChip::configure` — Rust-exact, INCLUDING CondSwap; nothing hand-inlined or omitted.
-- Exact Rust calls, in order (halo2_gadgets/src/sinsemilla/dump.rs::configure_merkle):
--   register_prereqs(meta)  [= the full sinsemillaPre chain, ending in SinsemillaChip::configure];
--   MerkleChip::configure(meta, sinsemilla_config), which itself calls, in order:
--     CondSwapChip::configure(meta, advices[0..5])  [q_swap + the 3-constraint swap gate];
--     meta.selector() (q_decompose) + the 4-constraint "Decomposition check" gate.
-- Post-compression activations gathered from `MerkleDumpCircuit::synthesize` (a real
-- `CondSwapChip::swap` then the real `MerkleChip::hash_layer`, Value::unknown witnesses, k=11).
-- Regenerate: cargo run -p halo2_gadgets --features dump-lean --bin dump_lean_sinsemilla -- <out_dir>
-- Selector-compression map (see `compress_selectors.rs`): per selector, the packed
-- fixed column, its combination length, and this selector's assigned root.
import Clean.Ironwood.Fixtures.FixtureTypes

namespace Halo2.Ironwood.Fixtures

open Halo2.Ironwood.Fixtures

def merkleSelMap : SelCompressMap :=
  { newFixedCols := 5,
    entries := [(0, ⟨6, 1, 1⟩),
      (1, ⟨7, 1, 1⟩),
      (2, ⟨9, 3, 1⟩),
      (3, ⟨8, 1, 1⟩),
      (4, ⟨9, 3, 2⟩),
      (5, ⟨10, 1, 1⟩),
      (6, ⟨9, 3, 3⟩)] }

end Halo2.Ironwood.Fixtures
