-- Auto-generated by halo2 `dump_lean` (Halo2-Clean VK-matching). Do not edit by hand.
-- Chain: the Sinsemilla prerequisite chain (see sinsemillaPre) continued by the real
-- `MerkleChip::configure` — Rust-exact, INCLUDING CondSwap; nothing hand-inlined or omitted.
-- Exact Rust calls, in order (halo2_gadgets/src/sinsemilla/dump.rs::configure_merkle):
--   register_prereqs(meta)  [= the full sinsemillaPre chain, ending in SinsemillaChip::configure];
--   MerkleChip::configure(meta, sinsemilla_config), which itself calls, in order:
--     CondSwapChip::configure(meta, advices[0..5])  [q_swap + the 3-constraint swap gate];
--     meta.selector() (q_decompose) + the 4-constraint "Decomposition check" gate.
-- Post-compression activations gathered from `MerkleDumpCircuit::synthesize` (a real
-- `CondSwapChip::swap` then the real `MerkleChip::hash_layer`, Value::unknown witnesses, k=11).
-- Regenerate: cargo run -p halo2_gadgets --features dump-lean --bin dump_lean_sinsemilla -- <out_dir>
import Clean.Ironwood.Fixtures.FixtureTypes

namespace Halo2.Ironwood.Fixtures

open Halo2.Ironwood.Fixtures

def merklePre : CsFixture :=
  { numAdviceColumns := 10,
    numFixedColumns := 6,
    numInstanceColumns := 0,
    numSelectors := 7,
    adviceQueryLayout := [(9, 0), (9, 1), (9, -1), (0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (2, 1), (3, 1), (0, 1), (4, 1), (1, 1)],
    fixedQueryLayout := [(0, 0), (2, 0), (5, 0), (3, 0), (4, 0), (1, 0)],
    instanceQueryLayout := [],
    gates := [(.product (.selector 2) (.sum (.product (.scaled (.advice 2) (mkFp 1024 0 0 0)) (.advice 1)) (.negated (.advice 0)))),
      (.product (.selector 4) (.sum (.scaled (.fixed 5) (mkFp 2 0 0 0)) (.negated (.product (.sum (.advice 6) (.advice 7)) (.sum (.advice 3) (.negated (.sum (.sum (.product (.advice 6) (.advice 6)) (.negated (.advice 3))) (.negated (.advice 4))))))))),
      (.product (.selector 3) (.sum (.product (.advice 7) (.advice 7)) (.negated (.sum (.sum (.advice 10) (.sum (.sum (.product (.advice 6) (.advice 6)) (.negated (.advice 3))) (.negated (.advice 4)))) (.advice 3))))),
      (.product (.selector 3) (.sum (.product (.scaled (.advice 7) (mkFp 4 0 0 0)) (.sum (.advice 3) (.negated (.advice 10)))) (.negated (.sum (.sum (.scaled (.product (.sum (.advice 6) (.advice 7)) (.sum (.advice 3) (.negated (.sum (.sum (.product (.advice 6) (.advice 6)) (.negated (.advice 3))) (.negated (.advice 4)))))) (mkFp 2 0 0 0)) (.product (.sum (.constant (mkFp 2 0 0 0)) (.negated (.product (.fixed 2) (.sum (.fixed 2) (.negated (.constant (mkFp 1 0 0 0))))))) (.product (.sum (.advice 9) (.advice 11)) (.sum (.advice 10) (.negated (.sum (.sum (.product (.advice 9) (.advice 9)) (.negated (.advice 10))) (.negated (.advice 12)))))))) (.product (.scaled (.product (.fixed 2) (.sum (.fixed 2) (.negated (.constant (mkFp 1 0 0 0))))) (mkFp 2 0 0 0)) (.advice 9)))))),
      (.product (.selector 5) (.sum (.advice 5) (.negated (.sum (.product (.advice 7) (.advice 4)) (.product (.sum (.constant (mkFp 1 0 0 0)) (.negated (.advice 7))) (.advice 3)))))),
      (.product (.selector 5) (.sum (.advice 6) (.negated (.sum (.product (.advice 7) (.advice 3)) (.product (.sum (.constant (mkFp 1 0 0 0)) (.negated (.advice 7))) (.advice 4)))))),
      (.product (.selector 5) (.product (.advice 7) (.sum (.constant (mkFp 1 0 0 0)) (.negated (.advice 7))))),
      (.product (.selector 6) (.sum (.sum (.advice 3) (.negated (.scaled (.advice 10) (mkFp 1024 0 0 0)))) (.negated (.advice 11)))),
      (.product (.selector 6) (.sum (.sum (.advice 10) (.scaled (.sum (.sum (.advice 4) (.negated (.scaled (.advice 12) (mkFp 1024 0 0 0)))) (.scaled (.advice 8) (mkFp 1024 0 0 0))) (mkFp 0 0 0 281474976710656))) (.negated (.advice 6)))),
      (.product (.selector 6) (.sum (.sum (.advice 9) (.scaled (.advice 5) (mkFp 32 0 0 0))) (.negated (.advice 7)))),
      (.product (.selector 6) (.sum (.advice 12) (.negated (.sum (.advice 8) (.scaled (.advice 9) (mkFp 32 0 0 0))))))],
    lookups := [({ inputs := [(.product (.selector 0) (.sum (.product (.selector 1) (.sum (.advice 0) (.negated (.scaled (.advice 1) (mkFp 1024 0 0 0))))) (.product (.sum (.constant (mkFp 1 0 0 0)) (.negated (.selector 1))) (.advice 0))))], tables := [(.fixed 1)] } : LookupFixture),
      ({ inputs := [(.product (.selector 3) (.sum (.advice 5) (.negated (.scaled (.product (.sum (.fixed 2) (.negated (.product (.fixed 2) (.sum (.fixed 2) (.negated (.constant (mkFp 1 0 0 0))))))) (.advice 8)) (mkFp 1024 0 0 0))))), (.sum (.product (.selector 3) (.advice 4)) (.scaled (.sum (.constant (mkFp 1 0 0 0)) (.negated (.selector 3))) (mkFp 6526256343580731999 2999498162208400053 1455178258206882939 987732578029543183))), (.sum (.product (.selector 3) (.sum (.scaled (.product (.sum (.advice 6) (.advice 7)) (.sum (.advice 3) (.negated (.sum (.sum (.product (.advice 6) (.advice 6)) (.negated (.advice 3))) (.negated (.advice 4)))))) (mkFp 14742138064964943873 1234914826957257869 0 2305843009213693952)) (.negated (.product (.advice 6) (.sum (.advice 3) (.negated (.advice 4))))))) (.scaled (.sum (.constant (mkFp 1 0 0 0)) (.negated (.selector 3))) (mkFp 1712018179792725123 10685357584973937153 11290355119345096144 3391000250449829916)))], tables := [(.fixed 1), (.fixed 3), (.fixed 4)] } : LookupFixture)] }

end Halo2.Ironwood.Fixtures
