-- Auto-generated by `poseidon::layout_dump::dump_layout_poseidon` (sibling halo2 checkout).
-- Do not edit by hand. Regenerate:
--   cargo test --release -p halo2_gadgets --lib poseidon::layout_dump -- --nocapture
import Clean.Ironwood.Fixtures.FixtureTypes

namespace Halo2.Ironwood.Fixtures

open Halo2.Ironwood.Fixtures

def poseidonSelMap : SelCompressMap :=
  { newFixedCols := 3,
    entries := [(0, ⟨8, 1, 1⟩),
      (1, ⟨9, 1, 1⟩),
      (2, ⟨10, 1, 1⟩)] }

end Halo2.Ironwood.Fixtures
