-- Auto-generated by halo2 `dump_lean` (Halo2-Clean VK-matching). Do not edit by hand.
-- Chain: orchard merkle_config_1 prerequisites + the real `SinsemillaChip::configure`.
-- Exact Rust calls, in order (halo2_gadgets/src/sinsemilla/dump.rs::register_prereqs):
--   meta.advice_column() x10; meta.fixed_column() + meta.enable_constant() (constants);
--   meta.fixed_column() (fixed_y_q); meta.lookup_table_column() x3;
--   PallasLookupRangeCheckConfig::configure(meta, advices[9], lookup.0);
--   SinsemillaChip::configure(meta, advices[0..5], advices[6], fixed_y_q, lookup,
--     range_check, /*allow_init_from_private_point=*/ false).
-- Post-compression activations gathered from `SinsemillaDumpCircuit::synthesize` (one real
-- `hash_to_point` + the b_1/b_2 short range checks, Value::unknown witnesses, k=11).
-- Regenerate: cargo run -p halo2_gadgets --features dump-lean --bin dump_lean_sinsemilla -- <out_dir>
import Clean.Ironwood.Fixtures.FixtureTypes

namespace Halo2.Ironwood.Fixtures

open Halo2.Ironwood.Fixtures

def sinsemillaPost : CsFixture :=
  { numAdviceColumns := 10,
    numFixedColumns := 11,
    numInstanceColumns := 0,
    numSelectors := 5,
    adviceQueryLayout := [(9, 0), (9, 1), (9, -1), (0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (2, 1), (3, 1), (0, 1), (4, 1), (1, 1)],
    fixedQueryLayout := [(0, 0), (2, 0), (5, 0), (3, 0), (4, 0), (1, 0), (6, 0), (7, 0), (8, 0), (9, 0), (10, 0)],
    instanceQueryLayout := [],
    gates := [(.product (.fixed 9) (.sum (.product (.scaled (.advice 2) (mkFp 1024 0 0 0)) (.advice 1)) (.negated (.advice 0)))),
      (.product (.fixed 10) (.sum (.scaled (.fixed 5) (mkFp 2 0 0 0)) (.negated (.product (.sum (.advice 6) (.advice 7)) (.sum (.advice 3) (.negated (.sum (.sum (.product (.advice 6) (.advice 6)) (.negated (.advice 3))) (.negated (.advice 4))))))))),
      (.product (.fixed 8) (.sum (.product (.advice 7) (.advice 7)) (.negated (.sum (.sum (.advice 10) (.sum (.sum (.product (.advice 6) (.advice 6)) (.negated (.advice 3))) (.negated (.advice 4)))) (.advice 3))))),
      (.product (.fixed 8) (.sum (.product (.scaled (.advice 7) (mkFp 4 0 0 0)) (.sum (.advice 3) (.negated (.advice 10)))) (.negated (.sum (.sum (.scaled (.product (.sum (.advice 6) (.advice 7)) (.sum (.advice 3) (.negated (.sum (.sum (.product (.advice 6) (.advice 6)) (.negated (.advice 3))) (.negated (.advice 4)))))) (mkFp 2 0 0 0)) (.product (.sum (.constant (mkFp 2 0 0 0)) (.negated (.product (.fixed 2) (.sum (.fixed 2) (.negated (.constant (mkFp 1 0 0 0))))))) (.product (.sum (.advice 9) (.advice 11)) (.sum (.advice 10) (.negated (.sum (.sum (.product (.advice 9) (.advice 9)) (.negated (.advice 10))) (.negated (.advice 12)))))))) (.product (.scaled (.product (.fixed 2) (.sum (.fixed 2) (.negated (.constant (mkFp 1 0 0 0))))) (mkFp 2 0 0 0)) (.advice 9))))))],
    lookups := [({ inputs := [(.product (.fixed 6) (.sum (.product (.fixed 7) (.sum (.advice 0) (.negated (.scaled (.advice 1) (mkFp 1024 0 0 0))))) (.product (.sum (.constant (mkFp 1 0 0 0)) (.negated (.fixed 7))) (.advice 0))))], tables := [(.fixed 1)] } : LookupFixture),
      ({ inputs := [(.product (.fixed 8) (.sum (.advice 5) (.negated (.scaled (.product (.sum (.fixed 2) (.negated (.product (.fixed 2) (.sum (.fixed 2) (.negated (.constant (mkFp 1 0 0 0))))))) (.advice 8)) (mkFp 1024 0 0 0))))), (.sum (.product (.fixed 8) (.advice 4)) (.scaled (.sum (.constant (mkFp 1 0 0 0)) (.negated (.fixed 8))) (mkFp 6526256343580731999 2999498162208400053 1455178258206882939 987732578029543183))), (.sum (.product (.fixed 8) (.sum (.scaled (.product (.sum (.advice 6) (.advice 7)) (.sum (.advice 3) (.negated (.sum (.sum (.product (.advice 6) (.advice 6)) (.negated (.advice 3))) (.negated (.advice 4)))))) (mkFp 14742138064964943873 1234914826957257869 0 2305843009213693952)) (.negated (.product (.advice 6) (.sum (.advice 3) (.negated (.advice 4))))))) (.scaled (.sum (.constant (mkFp 1 0 0 0)) (.negated (.fixed 8))) (mkFp 1712018179792725123 10685357584973937153 11290355119345096144 3391000250449829916)))], tables := [(.fixed 1), (.fixed 3), (.fixed 4)] } : LookupFixture)] }

end Halo2.Ironwood.Fixtures
