/-
Witness generation for the transition-AIR ensemble: executable evidence that
`fibonacciTransitionEnsemble.ensemble.Statement` is satisfiable. The mirror of
`Clean/Examples/FibonacciVm/WitnessGenerationTest.lean`, differing in that the Fibonacci table is
generated by `Mode.transition` (a seed row plus a chain, instead of demand handling), where to
stop is delivered through a runtime `ProverHint`, padding continues the chain with frozen rows,
and `boundariesHold` joins `constraintsHold` and `channelsBalanced`.
-/
import Clean.Examples.FibonacciTransition
import Clean.Air.Extraction.Lower
import Clean.Utils.Primes

namespace Air.Flat.TransitionWitnessGenerationTest

open Air.Flat.WitnessGeneration
open Clean.Examples.FibonacciTransition

/-- The number of enabled Fibonacci steps the prover intends to run. -/
private def steps : ℕ := 20

/-- The step count, delivered the only way generation-only knowledge travels: as an
uncommitted runtime hint. Nothing else about the trace depends on the public claim. -/
private def hints : ProverHint (F pBabybear) := fun key n =>
  if key = "fibonacci-steps" then
    match n with
    | 1 => #[#v[(steps : F pBabybear)]]
    | _ => #[]
  else #[]

/-- Chained generation for the transition table: the seed row `(1, 0, 0, 1)` plus one
committed row per enabled step. -/
private def fibTransitionMode : Mode (F pBabybear) := .transition {
  rows := steps + 1
  seed := .ofFExprs #v[1, 0, 0, 1]
  seed_valid := by rfl
}

/-- Generation metadata aligned with
`fibonacciTransitionEnsemble.ensemble.tables = [fibonacci-transition, add8, bytes]`; the add8 and
bytes modes are the VM ensemble's, unchanged. The transition table's padding input is irrelevant,
since its padding rows continue the chain. -/
private def config (fuel : ℕ) : Config (F pBabybear) unit where
  modes := [fibTransitionMode, FibonacciWitness.add8Mode, FibonacciWitness.bytesMode]
  padding := [
    { input := #[] },
    { input := #[0, 0, 0, 0], minimumRows := 32 },
    { input := #[0, 0], minimumRows := 256 }
  ]
  fuel := fuel
  hint := hints

private def runGeneration (publicInput : fieldTriple (F pBabybear)) (fuel : ℕ) :
    Except String (EnsembleWitness (fibonacciTransitionEnsemble (p := pBabybear)).ensemble) :=
  generate (fibonacciTransitionEnsemble (p := pBabybear)).ensemble (config fuel) publicInput ()

private def publicInput : fieldTriple (F pBabybear) :=
  let state := fibonacci steps
  (steps, state.1, state.2)

private def result : Except String (List ℕ × Bool × Bool × Bool) :=
  match runGeneration publicInput 1000 with
  | .error error => .error error
  | .ok witness => .ok (
      witness.tables.map (·.length),
      constraintsHold witness,
      channelsBalanced witness,
      boundariesHold witness)

/-- The seed plus 20 chained steps commit 21 Fibonacci rows, padded to 32 by continuing the chain;
the 20 enabled rows' byte-add pulls create 20 addition rows padded to 32; byte range checks land in
the 256 preallocated byte rows. All three conjuncts of `Ensemble.Statement` hold. -/
example : result = .ok ([32, 32, 256], true, true, true) := by native_decide

private def traceRows : Except String (Bool × Bool × Bool) :=
  match runGeneration publicInput 1000 with
  | .error error => .error error
  | .ok witness =>
      match witness.tables with
      | fib :: _ =>
          let state := fibonacci steps
          let final : Array (F pBabybear) :=
            #[0, (steps : F pBabybear), (state.1 : F pBabybear), (state.2 : F pBabybear)]
          .ok (
            fib.table.head? == some #[1, 0, 0, 1],
            fib.table[steps]? == some final,
            fib.table.getLast? == some final)
      | _ => .error "ensemble has no Fibonacci table"

/-- The first committed row is the seed; the row after the 20th step is the frozen final
state `(0, 20, x₂₀, y₂₀)`; and the chain-padded last row still carries it -- the stutter
in action, which is what lets `finalAssertion` read the answer off the last row. -/
example : traceRows = .ok (true, true, true) := by native_decide

private def transitionData : Bool :=
  match runGeneration publicInput 1000 with
  | .error _ => false
  | .ok witness =>
      let rows := witness.data "fibonacci-transition" 4
      rows.size == 32 && match rows[0]? with
        | some row => row[0] == (1 : F pBabybear) && row[1] == 0 && row[2] == 0 && row[3] == 1
        | none => false

/-- A transition table owns each committed row wholly (`input_eq_rowWidth`), so it exports
entire rows -- chain-generated padding included -- as its `ProverData` inputs. -/
example : transitionData = true := by native_decide

private def wrongClaim : fieldTriple (F pBabybear) := (steps, 1, 2)

private def wrongClaimResult : Except String (Bool × Bool × Bool) :=
  match runGeneration wrongClaim 1000 with
  | .error error => .error error
  | .ok witness => .ok (constraintsHold witness, channelsBalanced witness, boundariesHold witness)

/-- Generation is hint-driven and the verifier is empty, so a false public claim still
yields a well-formed, channel-balanced trace: the boundary conjunct is the one that
catches the lie. -/
example : wrongClaimResult = .ok (true, true, false) := by native_decide

private def demandModeForTransition : Except String Unit :=
  let bad : Config (F pBabybear) unit :=
    { config 1000 with
        modes := [FibonacciWitness.fibMode, FibonacciWitness.add8Mode,
          FibonacciWitness.bytesMode] }
  (generate (fibonacciTransitionEnsemble (p := pBabybear)).ensemble bad publicInput ()).map
    fun _ => ()

/-- `validateModes` rejects demand generation for a two-row-window component up front. -/
example : demandModeForTransition = .error
    "component 'fibonacci-transition' spans 2 trace rows and requires transition generation" := by
  native_decide

private def transitionModeForFlat : Except String Unit :=
  let bad : Config (F pBabybear) unit :=
    { config 1000 with
        modes := [fibTransitionMode, fibTransitionMode, FibonacciWitness.bytesMode] }
  (generate (fibonacciTransitionEnsemble (p := pBabybear)).ensemble bad publicInput ()).map
    fun _ => ()

/-- ... and the converse: transition generation is rejected for a flat component. -/
example : transitionModeForFlat = .error
    "transition generation for component 'add8' requires a two-row window, found windowRows = 1" := by
  native_decide

private def extractionRejected : Bool :=
  match Air.Flat.Extraction.lower (fibonacciTransitionEnsemble (p := pBabybear)).ensemble
      (config 1000) with
  | .error (.boundaryAssertions 2) => true
  | _ => false

/-- The Rust backend expresses neither boundary assertions, two-row windows, nor transition
generation; `lower` refuses this ensemble at the first of those guards. The shipped-artifact
door demonstrably stays shut for the transition design. -/
example : extractionRejected = true := by native_decide

end Air.Flat.TransitionWitnessGenerationTest
