import Clean.Halo2.Fixtures.Layout
import Clean.Halo2.Fixtures.MerkleLayout
import Clean.Halo2.Fixtures.MerkleSelMap
import Clean.Halo2.Fixtures.MerklePost
import Clean.Halo2.Tests.TestVkLayoutSinsemilla
import Clean.Ironwood.Sinsemilla.Merkle

/-!
# VK-match test (Phase 2): the Merkle chain — LAYOUT (permutation σ + fixed values)

The layout counterpart of `TestVkMatchMerkle`. Mirrors `MerkleDumpCircuit::synthesize`
(`Value::sUnknown`, k=11) in the dump's exact region sequence — load the generator table,
witness the node, one real `CondSwapChip::swap`, one real `MerkleChip::hash_layer`
(= witness `a`, short-range-check `b_1`/`b_2`, witness `b`/`c`, `hash_to_point`, the
`"Check piece decomposition"` region) — using the real ported gadgets throughout
(`CondSwap.swap`, `HashLayer.synthesize`). The placement line was regenerated by the
sibling-checkout `sinsemilla::layout_dump` harness (copyList reproduced 17/17 — see the
fixture header).
-/

namespace Halo2.Fixtures.Test.LayoutMerkle

open Ironwood (Fp)
open Halo2.Fixtures.Layout
open Halo2.Fixtures.Test.LayoutSinsemilla (layoutG layoutQ sUnknown)

/-- The Merkle configure chain (the same allocation sequence as
`TestVkMatchMerkle.merkleProgram`), also returning the range-check config. -/
def mSetup : Ironwood.Sinsemilla.Merkle.Config × Ironwood.LookupRangeCheck.Config 10 :=
  let prog : Configure Fp
      (Ironwood.Sinsemilla.Merkle.Config × Ironwood.LookupRangeCheck.Config 10) := do
    let a0 ← adviceColumn; let a1 ← adviceColumn; let a2 ← adviceColumn
    let a3 ← adviceColumn; let a4 ← adviceColumn; let _a5 ← adviceColumn
    let a6 ← adviceColumn; let _a7 ← adviceColumn; let _a8 ← adviceColumn
    let a9 ← adviceColumn
    let constants ← fixedColumn
    enableConstant constants
    let fixedYQ ← fixedColumn
    let t0 ← lookupTableColumn
    let t1 ← lookupTableColumn
    let t2 ← lookupTableColumn
    let lookupConfig ← Ironwood.LookupRangeCheck.configure 10 a9 t0
    let scfg ← Ironwood.Sinsemilla.HashPiece.configure Test.sinsemillaTestG
      a0 a1 a2 a3 a4 a6 fixedYQ { tableIdx := t0, tableX := t1, tableY := t2 }
    let mcfg ← Ironwood.Sinsemilla.Merkle.configure scfg
    return (mcfg, lookupConfig)
  (prog {}).1

def mCfg : Ironwood.Sinsemilla.Merkle.Config := mSetup.1
def mLookupCfg : Ironwood.LookupRangeCheck.Config 10 := mSetup.2

/-- A dummy `Bool` witness (`Value::sUnknown`). -/
def unknownBool : Placed ProverEnvironment Fp → Bool := fun _ => false

/-- The Lean mirror of `MerkleDumpCircuit::synthesize`, on the real ported gadgets. -/
def merkleLayoutProgram : Circuit Fp Unit := do
  Ironwood.Sinsemilla.load layoutG mCfg.sinsemilla.generatorTable
  -- witness the node: advices[0] row 0
  let node ← assignRegion "witness node"
    (assignAdvice mCfg.sinsemilla.xA 0 sUnknown)
  -- the real CondSwapChip::swap
  let pair ← assignRegion "swap"
    ((Ironwood.CondSwap.swap sUnknown unknownBool).call mCfg.condSwap 0 { a := node })
  -- the real MerkleChip::hash_layer (l = 0)
  let _root ← Ironwood.Sinsemilla.Merkle.HashLayer.synthesize layoutG mCfg mLookupCfg
    layoutQ 0 { left := pair.aSwapped, right := pair.bSwapped }
  pure ()

def mOps : Operations Fp := merkleLayoutProgram.operations
def mRegions : List (ℕ × RegionOperations Fp) := (indexedRegions mOps 0).1

/-- Region starts from the fixture placements, in `assignRegion` order (the
`generator_table` slot is the three `loadTable`s' — filtered). -/
def mStarts : List ℕ :=
  ((merkleLayout.regions.filter (·.name ≠ "generator_table")).map (·.start))

def mPermCols : List ColRef := merkleLayout.permColumns

def mCopyList : List (ℕ × ℕ × ℕ × ℕ) :=
  copyList mPermCols mStarts mRegions merkleLayout.constants
def mSigma : List (ℕ × ℕ × ℕ × ℕ) :=
  sigmaEntries (runAssembly merkleLayout.n mPermCols.length mCopyList)
def mUsable : ℕ := usableRows merkleLayout.n merklePost.adviceQueryLayout
def mFixed : List (ℕ × ℕ × ℕ) :=
  sortFixed (dedupFixed
    (tableFixed (ZMod.val : Fp → ℕ) mUsable mOps
      ++ constantsFixed merkleLayout.constants
      ++ selectorFixed merkleSelMap (activations mStarts mRegions)
      ++ assignedFixed (ZMod.val : Fp → ℕ) mStarts mRegions))

/-! ## Machinery validation -/

#guard mUsable = 2042

-- keygen `Assembly` σ replay from the fixture's OWN ordered copy list.
#guard sigmaEntries (runAssembly merkleLayout.n mPermCols.length merkleLayout.copyList)
  = merkleLayout.sigma

-- Region lockstep: the fixture's non-table region names, in order, are this side's
-- assignRegion sequence.
#guard (merkleLayout.regions.filter (·.name ≠ "generator_table")).map (·.name)
  = ["witness node", "swap", "witness message piece", "Range check 5 bits",
     "Range check 5 bits", "witness message piece", "witness message piece",
     "hash_to_point", "Check piece decomposition"]

/-! ## End-to-end reconstruction vs the ported Merkle stack -/

-- the ordered copy list (order-sensitive — σ's cycle rotations depend on it)
#guard mCopyList = merkleLayout.copyList

-- the keygen permutation σ
#guard mSigma = merkleLayout.sigma

-- the full fixed contents
#guard mFixed = sortFixed merkleLayout.fixed

end Halo2.Fixtures.Test.LayoutMerkle
