import Clean.Halo2.Fixtures.Layout
import Clean.Halo2.Fixtures.BaseFieldLayout
import Clean.Halo2.Fixtures.BaseFieldSelMap
import Clean.Halo2.Fixtures.BaseFieldParams
import Clean.Ironwood.Ecc.MulFixed.BaseFieldElem

/-!
# VK-match test (layout): fixed-base mul by a base-field element — σ + fixed values

The `mul_fixed`/`base_field_elem` counterpart of `TestVkLayoutMul`, against fixtures
generated by our own sibling-checkout dumper
(`halo2_gadgets/src/ecc/chip/layout_dump.rs::dump_layout_base_field`; the fixture headers
carry the exact harness + regeneration command). It builds the Lean mirror of
`BaseFieldDumpCircuit::synthesize` — load the range-check table; witness `alpha`
(advice 0, row 0); run the ported `BaseFieldElem.synthesize` with the dumped
test-`BaseField` params — and reconstructs the keygen-view layout products with
`Fixtures.Layout`.

## What this pins

* the floor-planner region placements (incl. the SimpleFloorPlanner packing of the four
  base_field_elem pieces);
* the ORDERED raw copy list — the running-sum `z_0` copy, the incomplete-addition chain's
  self-copies, the cross-region acc/mul_b copies, the canonicity copies, and the
  strict-decomposition constants copy;
* the keygen permutation σ replayed from it;
* the full fixed contents: the lookup table (+ default fill), the 85-window Lagrange +
  `fixed_z` columns (the `assign_fixed_constants` values — the heart of the fixed-base
  VK), the constants column, and the post-compression packed-selector columns.

`#guard` equality is fine (D1).
-/

namespace Halo2.Fixtures.Test.LayoutBaseField

open Halo2.Ironwood (Fp)
open Halo2.Ironwood.Ecc.MulFixed (FixedBaseData)
open Halo2.Ironwood.Ecc.MulFixed.BaseFieldElem (Config configure)
open Halo2.Fixtures.Layout

/-- The harness config: the same configure chain as the Rust `BaseFieldDumpCircuit`
(10 advices, table column, 8 Lagrange fixed, constants, lookup on `a9`,
`add_incomplete(a0..a3)`, `add(a0..a8)`, `mul_fixed(lagrange, a4, a5)`,
`base_field_elem(a6..a8)`). -/
def setup : Config × (Fin 10 → Column .advice) × TableColumn :=
  let prog : Configure Fp (Config × (Fin 10 → Column .advice) × TableColumn) := do
    let a0 ← adviceColumn; let a1 ← adviceColumn; let a2 ← adviceColumn
    let a3 ← adviceColumn; let a4 ← adviceColumn; let a5 ← adviceColumn
    let a6 ← adviceColumn; let a7 ← adviceColumn; let a8 ← adviceColumn
    let a9 ← adviceColumn
    let tableIdx ← lookupTableColumn
    let l0 ← fixedColumn; let l1 ← fixedColumn; let l2 ← fixedColumn
    let l3 ← fixedColumn; let l4 ← fixedColumn; let l5 ← fixedColumn
    let l6 ← fixedColumn; let l7 ← fixedColumn
    let constants ← fixedColumn
    enableConstant constants
    let advices : Fin 10 → Column .advice := ![a0, a1, a2, a3, a4, a5, a6, a7, a8, a9]
    let lookupConfig ← Ironwood.LookupRangeCheck.configure 10 a9 tableIdx
    let addIncompleteConfig ← Ironwood.Ecc.AddIncomplete.add.configure (a0, a1, a2, a3)
    let addConfig ← Ironwood.Ecc.Add.add.configure (a0, a1, a2, a3, a4, a5, a6, a7, a8)
    let mulFixedConfig ← Ironwood.Ecc.MulFixed.configure
      ![l0, l1, l2, l3, l4, l5, l6, l7] a4 a5 addConfig addIncompleteConfig
    let cfg ← configure ![a6, a7, a8] lookupConfig mulFixedConfig
    return (cfg, advices, tableIdx)
  (prog {}).1

def bfCfg : Config := setup.1
def bfAdvices : Fin 10 → Column .advice := setup.2.1
def bfTableIdx : TableColumn := setup.2.2

/-- A dummy witness (keygen never reads advice values). -/
def unknown : WitgenIR Fp 1 := .native fun _ => #v[(0 : Fp)]

/-- The Lean mirror of `BaseFieldDumpCircuit::synthesize`: table load, witness alpha,
then the ported base-field-elem fixed-base mul with the dumped `BaseField` params. -/
def layoutProgram : Circuit Fp Unit := do
  loadTable bfTableIdx ((List.range (2 ^ 10)).map (Nat.cast : ℕ → Fp))
  let alpha ← assignRegion "witness alpha" (assignAdvice (bfAdvices 0) 0 unknown)
  let _ ← Ironwood.Ecc.MulFixed.BaseFieldElem.synthesize baseFieldData bfCfg alpha
  pure ()

/-- The reconstructed layout products, all from `layoutProgram.operations`. -/
def ops : Operations Fp := layoutProgram.operations
def starts : List ℕ := regionStarts ops baseFieldLayout
def regions : List (ℕ × RegionOperations Fp) := (indexedRegions ops 0).1
def permCols : List ColRef := baseFieldLayout.permColumns

def myCopyList : List (ℕ × ℕ × ℕ × ℕ) :=
  copyList permCols starts regions baseFieldLayout.constants
def mySigma : List (ℕ × ℕ × ℕ × ℕ) :=
  sigmaEntries (runAssembly baseFieldLayout.n permCols.length myCopyList)
/-- Usable rows `n − (blindingFactors + 1)` (blinding = 5 for this chain, from the dump's
META line). -/
def myUsable : ℕ := 2042
def myFixed : List (ℕ × ℕ × ℕ) :=
  allFixed (ZMod.val : Fp → ℕ) myUsable baseFieldSelMap ops starts regions
    baseFieldLayout.constants

/-! ## Machinery validation -/

-- Region-placement lockstep: the reconstructed slots consume the fixture's placements.
#guard starts = (baseFieldLayout.regions.filter (·.name ≠ "table_idx")).map (·.start)

-- keygen `Assembly` σ replay from the fixture's OWN copy list reproduces the fixture σ.
#guard sigmaEntries (runAssembly baseFieldLayout.n permCols.length baseFieldLayout.copyList)
  = baseFieldLayout.sigma

/-! ## End-to-end reconstruction vs the ported `BaseFieldElem.synthesize` -/

#guard myCopyList = baseFieldLayout.copyList
#guard mySigma = baseFieldLayout.sigma
#guard myFixed = sortFixed baseFieldLayout.fixed

/-- First index at which two lists differ — the diagnostic when a guard breaks. -/
def firstDiff {α : Type} [DecidableEq α] (a b : List α) : Option (ℕ × α × α) :=
  (a.zip b).zipIdx.findSome? fun ((x, y), i) => if x = y then none else some (i, x, y)

end Halo2.Fixtures.Test.LayoutBaseField
